export const products = [
  {
    key: "P1GREY",
    category: "Geanta",
    color: "gri",
    size: "big",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "P1GREY1.jpg",
    secondImage: "P1GREY2.jpg",
    images: [
      "P1GREY3.jpg",
      "P1GREY4.jpg",
      "P1GREY5.jpg",
      "P1GREY6.jpg",
      "P1GREY7.jpg",
      "P1GREY8.jpg",
    ],
    description:
      "Geanta are inaltimea de 20cm, lungimea de 24 cm si latimea de 12cm.",
    materials: "Este confectionata din",
  },
  {
    key: "P2F00CREM",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "P2CREM1.jpg",
    secondImage: "P2CREM2.jpg",
    images: ["P2CREM3.jpg"],
    description:
      "Geanta are inaltimea de 20cm, lungimea de 24 cm si latimea de 12cm.",
    materials: "Este confectionata din",
  },
  {
    key: "P2F00RED",
    category: "Geanta",
    color: "red",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "P2RED1.jpg",
    secondImage: "P2RED1.jpg",
    images: ["P2RED1.jpg"],
    description:
      "Geanta are inaltimea de 20cm, lungimea de 24 cm si latimea de 12cm.",
    materials: "Este confectionata din",
  },
  {
    key: "all-purse1",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    style: "elegante",
    firstImage: "purse1.jpg",
    secondImage: "purse1.jpg",
    images: ["purse1.jpg"],
  },
  {
    key: "P3F00VISINIU",
    category: "Geanta",
    color: "visiniu",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse-roxen-1.jpg",
    secondImage: "purse-roxen-2.jpg",
    images: ["purse-roxen-1.jpg"],
  },
  {
    key: "P3F00GREEN",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse-roxen-3.jpg",
    secondImage: "purse-roxen-3.jpg",
    images: ["purse-roxen-3.jpg"],
  },
  {
    key: "P3F00BLACK",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-roxen-4.jpg",
    secondImage: "purse-roxen-4.jpg",
    images: ["purse-roxen-4.jpg"],
  },
  {
    key: "P4F00PINK",
    category: "Geanta",
    color: "roz",
    size: "medium",
    material: "-",
    handle: "handle",
    style: "elegante",
    firstImage: "purse-felicia-1.jpeg",
    secondImage: "purse-felicia-1.jpeg",
    images: ["purse-felicia-1.jpeg"],
  },
  {
    key: "P4F00TURCOAZ",
    category: "Geanta",
    color: "turcoaz",
    size: "medium",
    material: "-",
    handle: "handle",
    style: "elegante",
    firstImage: "purse-felicia-2.jpeg",
    secondImage: "purse-felicia-2.jpeg",
    images: ["purse-felicia-2.jpeg"],
  },
  {
    key: "all-purse-sonia",
    category: "Geanta",
    color: "albastru",
    size: "mare",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-sonia-1.png",
    secondImage: "purse-sonia-1.png",
    images: ["purse-sonia-1.png"],
  },
  {
    key: "P6F00ORANGE",
    category: "Geanta",
    color: "portocaliu",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-florina-1.jpg",
    secondImage: "purse-florina-1.jpg",
    images: ["purse-florina-1.jpg"],
  },
  {
    key: "P5F00RED",
    category: "Geanta",
    color: "rosu",
    size: "medium",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-florina-2.jpg",
    secondImage: "purse-florina-3.jpg",
    images: ["purse-florina-2.jpg"],
  },
  {
    key: "P6F00GREEN",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-florina-4.jpg",
    secondImage: "purse-florina-4.jpg",
    images: ["purse-florina-4.jpg"],
  },
  {
    key: "P5F00GREEN",
    category: "Geanta",
    color: "verde",
    size: "medium",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse-florina-5.jpg",
    secondImage: "purse-florina-5.jpg",
    images: ["purse-florina-5.jpg"],
  },
  {
    key: "P7F00CREM",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse-andra-1.jpg",
    secondImage: "purse-andra-1.jpg",
    images: ["purse-andra-1.jpg"],
  },
  {
    key: "P7F00GREEN",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse-andra-2.jpg",
    secondImage: "purse-andra-5.jpg",
    images: ["purse-andra-2.jpg"],
  },
  {
    key: "P7F00PINK",
    category: "Geanta",
    color: "roz",
    size: "small",
    material: "-",
    handle: "handle",
    style: "elegante",
    firstImage: "purse-andra-6.jpg",
    secondImage: "purse-andra-4.jpg",
    images: ["purse-andra-4.jpg"],
  },
  {
    key: "P8F00BLUE",
    category: "Geanta",
    color: "turcoaz",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "purse6.jpg",
    secondImage: "purse6.jpg",
    images: ["purse6.jpg"],
  },
  {
    key: "P8F00BLACK",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "purse_black_rose.jpg",
    secondImage: "purse_black_rose.jpg",
    images: ["purse_black_rose.jpg"],
  },
  {
    key: "P9F00BLACK",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse_black_rose2.jpg",
    secondImage: "purse_black_rose2.jpg",
    images: ["purse_black_rose2.jpg"],
  },
  {
    key: "P8F00GREY",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual",
    firstImage: "purse_grey_rose.jpg",
    secondImage: "purse_grey_rose.jpg",
    images: ["purse_grey_rose.jpg"],
  },
  {
    key: "P9F00WHITE",
    category: "Geanta",
    color: "alb",
    size: "small",
    material: "-",
    handle: "strap",
    style: "elegante",
    firstImage: "purse_white_rose.jpg",
    secondImage: "purse_white_rose.jpg",
    images: ["purse_white_rose.jpg"],
  },
  {
    key: "P10F00GREY",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-1.jpg",
    secondImage: "purse-eliza-1.jpg",
    images: ["purse-eliza-1.jpg"],
  },
  {
    key: "all-purse-eliza-2",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-2.jpg",
    secondImage: "purse-eliza-2.jpg",
    images: ["purse-eliza-2.jpg"],
  },
  {
    key: "all-purse-eliza-3",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-3.jpg",
    secondImage: "purse-eliza-3.jpg",
    images: ["purse-eliza-3.jpg"],
  },
  {
    key: "all-purse-eliza-4",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-4.jpg",
    secondImage: "purse-eliza-4.jpg",
    images: ["purse-eliza-4.jpg"],
  },
  {
    key: "P10F00BLACK",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-10.jpg",
    secondImage: "purse-eliza-5.jpg",
    images: ["purse-eliza-8.jpg"],
  },
  {
    key: "P10F00WHITE",
    category: "Geanta",
    color: "alb",
    size: "small",
    material: "-",
    handle: "strap",
    style: "elegante",
    firstImage: "purse-eliza-6.jpg",
    secondImage: "purse-eliza-6.jpg",
    images: ["purse-eliza-6.jpg"],
  },
  {
    key: "P10F00BEJ",
    category: "Geanta",
    color: "bej",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-7.jpg",
    secondImage: "purse-eliza-7.jpg",
    images: ["purse-eliza-7.jpg"],
  },
  {
    key: "all-purse-eliza-9",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "purse-eliza-9.jpg",
    secondImage: "purse-eliza-9.jpg",
    images: ["purse-eliza-9.jpg"],
  },
  {
    key: "P11F00BEJ",
    category: "Geanta",
    color: "bej",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-1.jpg",
    secondImage: "purse-amalia-1.jpg",
    images: ["purse-amalia-1.jpg"],
  },
  {
    key: "P11F00PINK",
    category: "Geanta",
    color: "roz",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-2.jpg",
    secondImage: "purse-amalia-2.jpg",
    images: ["purse-amalia-2.jpg"],
  },
  {
    key: "P12F00BLACK",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    style: "casual-elegante",
    firstImage: "purse-amalia-3.jpg",
    secondImage: "purse-amalia-10.jpg",
    images: ["purse-amalia-3.jpg"],
  },
  {
    key: "P11F00BROWN",
    category: "Geanta",
    color: "maro",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-4.jpg",
    secondImage: "purse-amalia-4.jpg",
    images: ["purse-amalia-4.jpg"],
  },
  {
    key: "P11F00GREY",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-5.jpg",
    secondImage: "purse-amalia-5.jpg",
    images: ["purse-amalia-5.jpg"],
  },
  {
    key: "P11F00CREM",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-6.jpg",
    secondImage: "purse-amalia-6.jpg",
    images: ["purse-amalia-6.jpg"],
  },
  {
    key: "P11F00BLUE",
    category: "Geanta",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-7.jpg",
    secondImage: "purse-amalia-7.jpg",
    images: ["purse-amalia-7.jpg"],
  },
  {
    key: "P12F00BLUE",
    category: "Geanta",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-8.jpg",
    secondImage: "purse-amalia-8.jpg",
    images: ["purse-amalia-8.jpg"],
  },
  {
    key: "P11F00LIGHTGREY",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    style: "casual-elegante",
    firstImage: "purse-amalia-9.jpg",
    secondImage: "purse-amalia-9.jpg",
    images: ["purse-amalia-9.jpg"],
  },
  {
    key: "all-bag-1",
    category: "Rucsac",
    color: "negru",
    size: "big",
    material: "-",
    handle: "strap",
    style: "casual",
    firstImage: "bag.jpg",
    secondImage: "bag.jpg",
    images: ["bag.jpg"],
  },
  {
    key: "all-wallet-1",
    category: "Portofel",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "wallet1.jpg",
    secondImage: "wallet1.jpg",
    images: ["wallet1.jpg"],
  },
  {
    key: "all-wallet-2",
    category: "Portofel",
    color: "maro",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "wallet2.jpg",
    secondImage: "wallet2.jpg",
    images: ["wallet2.jpg"],
  },
  {
    key: "all-wallet-3",
    category: "Portofel",
    color: "rosu",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "wallet3.jpg",
    secondImage: "wallet3.jpg",
    images: ["wallet3.jpg"],
  },
  {
    key: "all-wallet-4",
    category: "Portofel",
    color: "verde",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "wallet4.jpg",
    secondImage: "wallet4.jpg",
    images: ["wallet4.jpg"],
  },
  {
    key: "all-wallet-5",
    category: "Portofel",
    color: "rosu",
    size: "small",
    material: "-",
    handle: "handle",
    style: "casual",
    firstImage: "wallet5.jpg",
    secondImage: "wallet5.jpg",
    images: ["wallet5.jpg"],
  },
  {
    key: "all-beret-adult-1",
    category: "Bereta",
    color: "negru",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual",
    firstImage: "beret1.jpg",
    secondImage: "beret1",
    images: ["beret1.jpg"],
  },
  {
    key: "all-beret-adult-2",
    category: "Bereta",
    color: "verde",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual",
    firstImage: "beret2.jpg",
    secondImage: "beret2.jpg",
    images: ["beret2.jpg"],
  },
  {
    key: "all-beret-adult-3",
    category: "Bereta",
    color: "albastru",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual",
    firstImage: "beret3.jpg",
    secondImage: "beret3.jpg",
    images: ["beret3.jpg"],
  },
  {
    key: "all-beret-adult-4",
    category: "Bereta",
    color: "gri",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual",
    firstImage: "beret4.jpg",
    secondImage: "beret4.jpg",
    images: ["beret4.jpg"],
  },
  {
    key: "all-beret-child-1",
    category: "Bereta",
    color: "rosu",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual",
    firstImage: "beret5.jpg",
    secondImage: "beret5.jpg",
    images: ["beret5.jpg"],
  },
  {
    key: "all-hat1",
    category: "Palarie",
    color: "violet",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat1.jpg",
    secondImage: "hat1.jpg",
    images: ["hat1.jpg"],
  },
  {
    key: "all-hat2",
    category: "Palarie",
    color: "crem",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat2.jpg",
    secondImage: "hat2.jpg",
    images: ["hat2.jpg"],
  },
  {
    key: "all-hat3",
    category: "Palarie",
    color: "maro",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat3.jpg",
    secondImage: "hat3.jpg",
    images: ["hat3.jpg"],
  },
  {
    key: "all-hat4",
    category: "Palarie",
    color: "bej",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat4.jpg",
    secondImage: "hat4.jpg",
    images: ["hat4.jpg"],
  },
  {
    key: "all-hat5",
    category: "Palarie",
    color: "gri",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat5.jpg",
    secondImage: "hat5.jpg",
    images: ["hat5.jpg"],
  },
  {
    key: "all-hat6",
    category: "Palarie",
    color: "crem",
    size: "universal",
    material: "-",
    handle: "-",
    style: "casual-elegante",
    firstImage: "hat6.jpg",
    secondImage: "hat6.jpg",
    images: ["hat6.jpg"],
  },
];
