export const products = [
  {
    key: "all-purse1",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "elegante",
    image: "purse1.jpg",
  },
  {
    key: "all-purse-roxen-1",
    category: "Geanta",
    color: "visiniu",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "purse-roxen-1.jpg",
  },
  {
    key: "all-purse-roxen-2",
    category: "Geanta",
    color: "visiniu",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse-roxen-2.jpg",
  },
  {
    key: "all-purse-roxen-3",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse-roxen-3.jpg",
  },
  {
    key: "all-purse-roxen-4",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-roxen-4.jpg",
  },
  {
    key: "all-purse-felicia-1",
    category: "Geanta",
    color: "roz",
    size: "medium",
    material: "-",
    handle: "handle",
    occasion: "elegante",
    image: "purse-felicia-1.jpeg",
  },
  {
    key: "all-purse-felicia-2",
    category: "Geanta",
    color: "turcoaz",
    size: "medium",
    material: "-",
    handle: "handle",
    occasion: "elegante",
    image: "purse-felicia-2.jpeg",
  },
  {
    key: "all-purse-sonia",
    category: "Geanta",
    color: "albastru",
    size: "mare",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-sonia-1.png",
  },
  {
    key: "all-purse-florina-1",
    category: "Geanta",
    color: "piersica",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-florina-1.jpg",
  },
  {
    key: "all-purse-florina-2",
    category: "Geanta",
    color: "rosu",
    size: "medium",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-florina-2.jpg",
  },
  {
    key: "all-purse-florina-3",
    category: "Geanta",
    color: "rosu",
    size: "medium",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-florina-3.jpg",
  },
  {
    key: "all-purse-florina-4",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-florina-4.jpg",
  },
  {
    key: "all-purse-florina-5",
    category: "Geanta",
    color: "verde",
    size: "medium",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse-florina-5.jpg",
  },
  {
    key: "all-purse-andra-1",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse-andra-1.jpg",
  },
  {
    key: "all-purse-andra-2",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse-andra-2.jpg",
  },
  {
    key: "all-purse-andra-4",
    category: "Geanta",
    color: "roz",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "elegante",
    image: "purse-andra-4.jpg",
  },
  {
    key: "all-purse-andra-5",
    category: "Geanta",
    color: "verde",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual-elegante",
    image: "purse-andra-5.jpg",
  },
  {
    key: "all-purse-andra-6",
    category: "Geanta",
    color: "roz",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "elegante",
    image: "purse-andra-6.jpg",
  },
  {
    key: "all-purse-rose-1",
    category: "Geanta",
    color: "Turcoaz",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "purse6.jpg",
  },
  {
    key: "all-purse-rose-2",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "purse_black_rose.jpg",
  },
  {
    key: "all-purse-rose-3",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse_black_rose2.jpg",
  },
  {
    key: "all-purse-rose-4",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual",
    image: "purse_grey_rose.jpg",
  },
  {
    key: "all-purse-rose-5",
    category: "Geanta",
    color: "alb",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "elegante",
    image: "purse_white_rose.jpg",
  },
  {
    key: "all-purse-eliza-1",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-1.jpg",
  },
  {
    key: "all-purse-eliza-2",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-2.jpg",
  },
  {
    key: "all-purse-eliza-3",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-3.jpg",
  },
  {
    key: "all-purse-eliza-4",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-4.jpg",
  },
  {
    key: "all-purse-eliza-5",
    category: "Geanta",
    color: "black",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-5.jpg",
  },
  {
    key: "all-purse-eliza-6",
    category: "Geanta",
    color: "alb",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "elegante",
    image: "purse-eliza-6.jpg",
  },
  {
    key: "all-purse-eliza-7",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-7.jpg",
  },
  {
    key: "all-purse-eliza-8",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-8.jpg",
  },
  {
    key: "all-purse-eliza-9",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-9.jpg",
  },
  {
    key: "all-purse-eliza-10",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-eliza-10.jpg",
  },
  {
    key: "all-purse-amalia-1",
    category: "Geanta",
    color: "bej",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-1.jpg",
  },
  {
    key: "all-purse-amalia-2",
    category: "Geanta",
    color: "roz",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-2.jpg",
  },
  {
    key: "all-purse-amalia-3",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual-elegante",
    image: "purse-amalia-3.jpg",
  },
  {
    key: "all-purse-amalia-4",
    category: "Geanta",
    color: "cafea",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-4.jpg",
  },
  {
    key: "all-purse-amalia-5",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-5.jpg",
  },
  {
    key: "all-purse-amalia-6",
    category: "Geanta",
    color: "crem",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-6.jpg",
  },
  {
    key: "all-purse-amalia-7",
    category: "Geanta",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-7.jpg",
  },
  {
    key: "all-purse-amalia-8",
    category: "Geanta",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-8.jpg",
  },
  {
    key: "all-purse-amalia-9",
    category: "Geanta",
    color: "gri",
    size: "small",
    material: "-",
    handle: "strap-handle",
    occasion: "casual-elegante",
    image: "purse-amalia-9.jpg",
  },
  {
    key: "all-purse-amalia-10",
    category: "Geanta",
    color: "negru",
    size: "small",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "purse-amalia-10.jpg",
  },
  {
    key: "all-bag-1",
    category: "Rucsac",
    color: "negru",
    size: "big",
    material: "-",
    handle: "strap",
    occasion: "casual",
    image: "bag.jpg",
  },
  {
    key: "all-wallet-1",
    category: "Portofel",
    color: "albastru",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "wallet1.jpg",
  },
  {
    key: "all-wallet-2",
    category: "Portofel",
    color: "Maro",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "wallet2.jpg",
  },
  {
    key: "all-wallet-3",
    category: "Portofel",
    color: "rosu",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "wallet3.jpg",
  },
  {
    key: "all-wallet-4",
    category: "Portofel",
    color: "verde",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "wallet4.jpg",
  },
  {
    key: "all-wallet-5",
    category: "Portofel",
    color: "rosu",
    size: "small",
    material: "-",
    handle: "handle",
    occasion: "casual",
    image: "wallet5.jpg",
  },
  {
    key: "all-beret-adult-1",
    category: "Bereta",
    color: "negru",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual",
    image: "beret1.jpg",
  },
  {
    key: "all-beret-adult-2",
    category: "Bereta",
    color: "verde",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual",
    image: "beret2.jpg",
  },
  {
    key: "all-beret-adult-3",
    category: "Bereta",
    color: "albastru",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual",
    image: "beret3.jpg",
  },
  {
    key: "all-beret-adult-4",
    category: "Bereta",
    color: "gri",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual",
    image: "beret4.jpg",
  },
  {
    key: "all-beret-child-1",
    category: "Bereta",
    color: "rosu",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual",
    image: "beret5.jpg",
  },
  {
    key: "all-hat1",
    category: "Palarie",
    color: "Mov",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat1.jpg",
  },
  {
    key: "all-hat2",
    category: "Palarie",
    color: "crem",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat2.jpg",
  },
  {
    key: "all-hat3",
    category: "Palarie",
    color: "Maro",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat3.jpg",
  },
  {
    key: "all-hat4",
    category: "Palarie",
    color: "bej",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat4.jpg",
  },
  {
    key: "all-hat5",
    category: "Palarie",
    color: "gri",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat5.jpg",
  },
  {
    key: "all-hat6",
    category: "Palarie",
    color: "crem",
    size: "universal",
    material: "-",
    handle: "-",
    occasion: "casual-elegante",
    image: "hat6.jpg",
  },
];
