import { productType } from "./types";

export const products: productType[] = [
  {
    key: "P15F00BLACK",
    name: "Geantă clutch de ocazie",
    category: "bag",
    color: "black",
    searchWords: ["poseta"],
    similarColors: ["grey", "white"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "clutch",
    firstImage: "P15BLACK1.jpg",
    secondImage: "P15BLACK2.jpg",
    images: ["P15BLACK3.jpg", "P15BLACK4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P16F00BEIGE",
    name: "Clutch de ocazie",
    category: "bag",
    color: "beige",
    searchWords: ["poseta"],
    similarColors: ["cream", "grey", "white"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "clutch",
    firstImage: "P16BEIGE1.jpg",
    secondImage: "P16BEIGE3.jpg",
    images: ["P16BEIGE2.jpg", "P16BEIGE4.jpg", "P16BEIGE5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P14F00BLUE",
    name: "Plic semioval",
    category: "bag",
    color: "blue",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "green", "grey"],
    size: "small",
    material: "-",
    handle: ["-"],
    style: "envelope",
    firstImage: "plic_semioval_2.jpg",
    secondImage: "plic_semioval_1.jpg",
    images: [
      "plic_semioval_3.jpg",
      "plic_semioval_5.jpg",
      "plic_semioval_4.jpg",
    ],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P20F00BROWN",
    name: "Geanta clutch de umar",
    category: "bag",
    color: "brown",
    searchWords: ["poseta"],
    similarColors: ["cream", "orange", "yellow", "red"],
    size: "medium",
    material: "-",
    handle: ["-"],
    style: "clutch",
    firstImage: "P20BROWN1.jpg",
    secondImage: "P20BROWN2.jpg",
    images: ["P20BROWN3.jpg", "P20BROWN4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },

  {
    key: "P1F00GREEN",
    name: "Geantă versatilă tip hexagon",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "hexagon",
    firstImage: "P1GREEN1.jpg",
    secondImage: "P1GREEN2.jpg",
    images: [
      "P1GREEN3.jpg",
      "P1GREEN4.jpg",
      "P1GREEN5.jpg",
      "P1GREEN6.jpg",
      "P1GREEN7.jpg",
    ],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },

  {
    key: "P25F00CREAM",
    category: "bag",
    color: "cream",
    searchWords: ["poseta", "crem"],
    similarColors: ["beige", "grey", "white"],
    size: "medium",
    material: "-",
    handle: ["", ""],
    style: "envelope",
    firstImage: "P25CREAM1.jpg",
    secondImage: "P25CREAM2.jpg",
    images: ["P25CREAM3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P23F00BLUE",
    name: "Geanta de umar tip buchet",
    category: "bag",
    color: "blue",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "green", "grey"],
    size: "big",
    material: "-",
    handle: ["strap"],
    style: "bouquet",
    firstImage: "P23BLUE1.jpg",
    secondImage: "P23BLUE2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P24F00BROWN",
    category: "bag",
    color: "brown",
    searchWords: ["poseta", "maro"],
    similarColors: ["burgundy", "red", "orange"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "P24BROWN1.jpg",
    secondImage: "P24BROWN3.jpg",
    images: ["P24BROWN2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P26F00CREAM",
    category: "bag",
    color: "cream",
    searchWords: ["poseta", "crem"],
    similarColors: ["beige", "grey", "white"],
    size: "medium",
    material: "-",
    handle: ["", ""],
    style: "elegante",
    firstImage: "P26CREAM3.jpg",
    secondImage: "P26CREAM2.jpg",
    images: ["P26CREAM1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P4F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "negru", "neagra"],
    similarColors: ["grey", "white"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "envelope",
    firstImage: "P4BLACK1.jpg",
    secondImage: "P4BLACK2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P22F00GREEN",
    name: "Geanta de umar tip buchet",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "medium",
    material: "-",
    handle: ["strap"],
    style: "bouquet",
    firstImage: "P22GREEN1.jpg",
    secondImage: "P22GREEN2.jpg",
    images: ["P22GREEN3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P28F00ORANGE",
    name: "Geantă cu cercuri",
    category: "bag",
    color: "orange",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "brown"],
    size: "medium",
    material: "-",
    handle: ["strap"],
    style: "circle",
    firstImage: "P28ORANGE2.jpg",
    secondImage: "P28ORANGE1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "S1F00PINK",
    name: "Pantofi model 1",
    category: "shoes",
    color: "pink",
    searchWords: [
      "pantofi",
      "papuci",
      "roz",
      "sireturi",
      "balerini",
      "sandale",
    ],
    similarColors: ["burgundy", "cream", "beige", "red"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S1PINK1.jpg",
    secondImage: "S1PINK2.jpg",
    images: ["S1PINK3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P27F00RED",
    category: "bag",
    color: "red",
    searchWords: ["poseta", "rosie"],
    similarColors: ["red", "burgundy", "pink"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "envelope",
    firstImage: "P27RED1.jpg",
    secondImage: "P27RED2.jpg",
    images: ["P27RED3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "B2F00GREEN",
    name: "Bereta model 2",
    category: "beret",
    color: "green",
    similarColors: ["blue", "turquoise"],
    searchWords: ["bereta", "basca", "bascuta", "verde"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "B2GREEN1.jpg",
    secondImage: "B2GREEN2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P3F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "P3BLACK1.jpg",
    secondImage: "P3BLACK3.jpg",
    images: ["P3BLACK2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },

  {
    key: "P23F00BROWN",
    name: "Geanta de umar tip buchet",
    category: "bag",
    color: "brown",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "green", "grey"],
    size: "big",
    material: "-",
    handle: ["strap"],
    style: "bouquet",
    firstImage: "P23BLUE3.jpg",
    secondImage: "P23BLUE4.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "W1F00BROWN",
    name: "Portofel cu margini rotunjite",
    category: "wallet",
    color: "brown",
    similarColors: ["orange", "red", "burgundy"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "W1BROWN2.jpg",
    secondImage: "W1BROWN1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "S2F00CREAM",
    name: "Pantofi model 2",
    category: "shoes",
    color: "cream",
    searchWords: ["pantofi", "balerini", "papuci", "CREM", "talpa", "sandale"],
    similarColors: ["grey", "beige", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S2CREAM2.jpg",
    secondImage: "S2CREAM1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P29F00GREEN",
    name: "Geantă de umar",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual-elegante",
    firstImage: "P29GREEN1.jpg",
    secondImage: "P29GREEN2.jpg",
    images: ["P29GREEN3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P19F00RED",
    name: "Geantă de umar",
    category: "bag",
    color: "red",
    searchWords: ["poseta"],
    similarColors: ["burgundy", "pink", "violet"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "casual-elegante",
    firstImage: "P19RED3.jpg",
    secondImage: "P19RED2.jpg",
    images: ["P19RED1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "B3F00PINK",
    name: "Bereta pentru copii",
    category: "beret",
    color: "pink",
    searchWords: ["bereta", "palarie", "copii"],
    similarColors: ["red", "pink", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "B3PINK1.jpg",
    secondImage: "B3PINK2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "B4F00PINK",
    name: "Bereta pentru copii",
    category: "beret",
    color: "pink",
    searchWords: ["bereta", "palarie", "copii", "fete", "fetite"],
    similarColors: ["red", "white", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "B4PINK2.jpg",
    secondImage: "B4PINK1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "B4F00WHITE",
    name: "Bereta pentru copii",
    category: "beret",
    color: "white",
    searchWords: ["bereta", "palarie", "copii", "fete", "fetite"],
    similarColors: ["red", "white", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "B4WHITE1.jpg",
    secondImage: "B4WHITE2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "C1F00PINK",
    name: "Caciulita pentru copii",
    category: "beanies",
    color: "pink",
    searchWords: ["caciulita", "caciula", "fes", "copii", "fete", "fetite"],
    similarColors: ["red", "white", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "C1PINK1.jpg",
    secondImage: "C1PINK1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "C2F00PINK",
    name: "Caciulita cu urechiuse pentru copii",
    category: "beanies",
    color: "pink",
    searchWords: ["caciulita", "caciula", "fes", "copii", "fete", "fetite"],
    similarColors: ["red", "white", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "C2PINK1.jpg",
    secondImage: "C2PINK1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "B1F00PINK",
    name: "Bereta pentru copii",
    category: "beret",
    color: "pink",
    searchWords: ["bereta", "palarie", "copii", "fete", "fetite"],
    similarColors: ["red", "white", "violet"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "B1PINK1.jpg",
    secondImage: "B1PINK1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P30F00BURGUNDY",
    name: "Geantă de umar",
    category: "bag",
    color: "burgundy",
    searchWords: ["poseta"],
    similarColors: ["red", "pink", "violet"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual-elegante",
    firstImage: "P30BURGUNDY1.jpg",
    secondImage: "P30BURGUNDY2.jpg",
    images: ["P30BURGUNDY3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P17F00GREY",
    name: "Geantă de mană tip scoică",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "white"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "casual-elegante",
    firstImage: "P17GREY1.jpg",
    secondImage: "P17GREY2.jpg",
    images: [""],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "B2F00GREY",
    name: "Bereta model 1",
    category: "beret",
    color: "grey",
    similarColors: ["cream", "beige", "white"],
    searchWords: ["bereta", "basca", "bascuta", "gri", "crem", "bej"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "B2GREY1.jpg",
    secondImage: "B2GREY2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P21F00RED",
    name: "Geantă de umar",
    category: "bag",
    color: "red",
    searchWords: ["poseta"],
    similarColors: ["burgundy", "pink", "violet"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "casual-elegante",
    firstImage: "P21RED4.jpg",
    secondImage: "P21RED2.jpg",
    images: ["P21RED1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P18F00GREY",
    name: "Geantă de mană",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "white"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "casual-elegante",
    firstImage: "P18GREY1.jpg",
    secondImage: "P18GREY2.jpg",
    images: ["P18GREY3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },

  {
    key: "P1F00GREY",
    name: "Geantă versatilă tip hexagon",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "hexagon",
    firstImage: "P1GREY1.jpg",
    secondImage: "P1GREY21.jpg",
    images: [
      "P1GREY31.jpg",
      "P1GREY41.jpg",
      "P1GREY51.jpg",
      "P1GREY61.jpg",
      "P1GREY71.jpg",
      "P1GREY81.jpg",
    ],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "S1F00DARKBEIGE",
    name: "Pantofi model 1",
    category: "shoes",
    color: "darkbeige",
    searchWords: [
      "pantofi",
      "papuci",
      "bej",
      "gri",
      "maro",
      "sireturi",
      "balerini",
      "sandale",
    ],
    similarColors: ["beige", "grey", "brown", "cream"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S1DARKBEIGE1.jpg",
    secondImage: "S1DARKBEIGE2.jpg",
    images: ["S1DARKBEIGE3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "S1F00ORANGE",
    name: "Pantofi model 1",
    category: "shoes",
    color: "orange",
    searchWords: [
      "pantofi",
      "papuci",
      "frez",
      "roz",
      "sireturi",
      "balerini",
      "sandale",
    ],
    similarColors: ["cream", "beige", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S1ORANGE1.jpg",
    secondImage: "S1ORANGE2.jpg",
    images: ["S1ORANGE3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P1F00BEIGE",
    name: "Geantă versatilă tip hexagon",
    category: "bag",
    color: "beige",
    searchWords: ["poseta"],
    similarColors: ["cream", "grey", "white"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "hexagon",
    firstImage: "P1BEIGE1.jpg",
    secondImage: "P1BEIGE2.jpg",
    images: ["P1BEIGE3.jpg", "P1BEIGE4.jpg", "P1BEIGE5.jpg", "P1BEIGE6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P1F00ORANGE",
    name: "Geantă versatilă tip hexagon",
    category: "bag",
    color: "orange",
    searchWords: ["poseta", "portocalie"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "hexagon",
    firstImage: "P1ORANGE1.jpg",
    secondImage: "P1ORANGE2.jpg",
    images: ["P1ORANGE3.jpg", "P1ORANGE4.jpg", "P1ORANGE5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P1F00BLACK",
    name: "Geantă versatilă tip hexagon",
    category: "bag",
    color: "black",
    searchWords: ["poseta"],
    similarColors: ["grey", "white"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: "hexagon",
    firstImage: "P1BLACK3.jpg",
    secondImage: "P1BLACK2.jpg",
    images: ["P1BLACK1.jpg", "P1BLACK4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },

  {
    key: "P2F00CREAM",
    category: "bag",
    color: "cream",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "P2CREAM2.jpg",
    secondImage: "P2CREAM3.jpg",
    images: ["P2CREAM1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P2F00RED",
    category: "bag",
    color: "red",
    searchWords: ["poseta", "rosie"],
    similarColors: ["red", "burgundy", "pink"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "P2RED3.jpg",
    secondImage: "P2RED1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P2F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "P2BLACK2.jpg",
    secondImage: "P2BLACK1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P13F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "elegante",
    firstImage: "purse1.jpg",
    secondImage: "purse1.jpg",
    images: ["purse1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P3F00BURGUNDY",
    category: "bag",
    color: "burgundy",
    searchWords: ["poseta", "visinie"],
    similarColors: ["burgundy", "red", "violet"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse-roxen-1.jpg",
    secondImage: "purse-roxen-2.jpg",
    images: ["purse-roxen-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P3F00GREEN",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse-roxen-3.jpg",
    secondImage: "purse-roxen-3.jpg",
    images: ["purse-roxen-3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "W2F00BLACK",
    name: "Portofel cu margini drepte",
    category: "wallet",
    color: "black",
    similarColors: ["grey", "white"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "W2BLACK1.jpg",
    secondImage: "W2BLACK2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P4F00TURQUOISE",
    category: "bag",
    color: "turquoise",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "green", "blue"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "elegante",
    firstImage: "P4TURQUOISE1.jpg",
    secondImage: "P4TURQUOISE2.jpg",
    images: ["P4TURQUOISE3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-sonia",
    category: "bag",
    color: "blue",
    searchWords: ["poseta", "albastra"],
    similarColors: ["blue", "turquoise", "green"],
    size: "large",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-sonia-1.png",
    secondImage: "purse-sonia-1.png",
    images: ["purse-sonia-1.png"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "S2F00GREY",
    name: "Pantofi model 2",
    category: "shoes",
    color: "grey",
    searchWords: ["pantofi", "balerini", "papuci", "gri", "talpa", "sandale"],
    similarColors: ["cream", "beige", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S2GREY2.jpg",
    secondImage: "S2GREY1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P6F00ORANGE",
    category: "bag",
    color: "orange",
    searchWords: ["poseta", "portocalie"],
    similarColors: ["orange", "red", "cream", "brown"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-florina-1.jpg",
    secondImage: "purse-florina-1.jpg",
    images: ["purse-florina-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P5F00RED",
    category: "bag",
    color: "red",
    searchWords: ["poseta", "rosie"],
    similarColors: ["red", "burgundy", "pink"],
    size: "medium",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-florina-2.jpg",
    secondImage: "purse-florina-3.jpg",
    images: ["purse-florina-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P6F00GREEN",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-florina-4.jpg",
    secondImage: "purse-florina-4.jpg",
    images: ["purse-florina-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "S2F00BEIGE",
    name: "Pantofi model 2",
    category: "shoes",
    color: "beige",
    searchWords: [
      "pantofi",
      "balerini",
      "papuci",
      "bej",
      "crem",
      "talpa",
      "sandale",
    ],
    similarColors: ["cream", "grey", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S2BEIGE2.jpg",
    secondImage: "S2BEIGE1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P5F00GREEN",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "medium",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse-florina-5.jpg",
    secondImage: "purse-florina-5.jpg",
    images: ["purse-florina-5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00CREAM",
    category: "bag",
    color: "cream",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse-andra-1.jpg",
    secondImage: "purse-andra-1.jpg",
    images: ["purse-andra-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00GREEN",
    category: "bag",
    color: "green",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse-andra-2.jpg",
    secondImage: "purse-andra-5.jpg",
    images: ["purse-andra-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00PINK",
    category: "bag",
    color: "pink",
    searchWords: ["poseta"],
    similarColors: ["pink", "burgundy", "violet", "red"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "elegante",
    firstImage: "purse-andra-6.jpg",
    secondImage: "purse-andra-4.jpg",
    images: ["purse-andra-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00BLUE",
    category: "bag",
    color: "turquoise",
    searchWords: ["poseta"],
    similarColors: ["turquoise", "green", "blue"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "purse6.jpg",
    secondImage: "purse6.jpg",
    images: ["purse6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "purse_black_rose.jpg",
    secondImage: "purse_black_rose.jpg",
    images: ["purse_black_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P9F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse_black_rose2.jpg",
    secondImage: "purse_black_rose2.jpg",
    images: ["purse_black_rose2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00GREY",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual",
    firstImage: "purse_grey_rose.jpg",
    secondImage: "purse_grey_rose.jpg",
    images: ["purse_grey_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P9F00WHITE",
    category: "bag",
    color: "white",
    searchWords: ["poseta", "alba"],
    similarColors: ["white", "cream", "beige", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "elegante",
    firstImage: "purse_white_rose.jpg",
    secondImage: "purse_white_rose.jpg",
    images: ["purse_white_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00GREY",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-eliza-1.jpg",
    secondImage: "purse-eliza-1.jpg",
    images: ["purse-eliza-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-2",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-eliza-2.jpg",
    secondImage: "purse-eliza-2.jpg",
    images: ["purse-eliza-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-eliza-10.jpg",
    secondImage: "purse-eliza-5.jpg",
    images: ["purse-eliza-8.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00WHITE",
    category: "bag",
    color: "white",
    searchWords: ["poseta", "alba"],
    similarColors: ["white", "cream", "beige", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "elegante",
    firstImage: "purse-eliza-6.jpg",
    secondImage: "purse-eliza-6.jpg",
    images: ["purse-eliza-6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "S1F00GREY",
    name: "Pantofi model 1",
    category: "shoes",
    color: "grey",
    searchWords: [
      "pantofi",
      "papuci",
      "gri",
      "sireturi",
      "balerini",
      "sandale",
    ],
    similarColors: ["cream", "beige", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual-elegante",
    firstImage: "S1GREY1.jpg",
    secondImage: "S1GREY2.jpg",
    images: ["S1GREY3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P10F00BEIGE",
    category: "bag",
    color: "beige",
    searchWords: ["poseta"],
    similarColors: ["beige", "cream", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-eliza-7.jpg",
    secondImage: "purse-eliza-7.jpg",
    images: ["purse-eliza-7.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-9",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "purse-eliza-9.jpg",
    secondImage: "purse-eliza-9.jpg",
    images: ["purse-eliza-9.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P4F00PINK",
    category: "bag",
    color: "pink",
    searchWords: ["poseta"],
    similarColors: ["pink", "burgundy", "violet", "red"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: "envelope",
    firstImage: "P4PINK1.jpg",
    secondImage: "P4PINK2.jpg",
    images: ["P4PINK3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00BEIGE",
    category: "bag",
    color: "beige",
    searchWords: ["poseta"],
    similarColors: ["beige", "cream", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "P11BEIGE2.jpg",
    secondImage: "P11BEIGE1.jpg",
    images: ["P11BEIGE3.jpg", "P11BEIGE4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00PINK",
    category: "bag",
    color: "pink",
    searchWords: ["poseta"],
    similarColors: ["pink", "burgundy", "violet", "red"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-2.jpg",
    secondImage: "purse-amalia-2.jpg",
    images: ["purse-amalia-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P12F00BLACK",
    category: "bag",
    color: "black",
    searchWords: ["poseta", "neagra"],
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: "casual_elegante",
    firstImage: "P12BLACK2.jpg",
    secondImage: "P12BLACK3.jpg",
    images: ["P12BLACK1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00DARKBEIGE",
    category: "bag",
    color: "darkbeige",
    searchWords: ["poseta"],
    similarColors: ["brown", "beige", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-4.jpg",
    secondImage: "purse-amalia-4.jpg",
    images: ["purse-amalia-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00GREY",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-5.jpg",
    secondImage: "purse-amalia-5.jpg",
    images: ["purse-amalia-5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00CREAM",
    category: "bag",
    color: "cream",
    searchWords: ["poseta"],
    similarColors: ["cream", "beige", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-6.jpg",
    secondImage: "purse-amalia-6.jpg",
    images: ["purse-amalia-6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00BLUE",
    category: "bag",
    color: "blue",
    searchWords: ["poseta", "albastra"],
    similarColors: ["blue", "turquoise", "green"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-7.jpg",
    secondImage: "purse-amalia-7.jpg",
    images: ["purse-amalia-7.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P12F00BLUE",
    category: "bag",
    color: "blue",
    searchWords: ["poseta", "albastra"],
    similarColors: ["blue", "turquoise", "green"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "purse-amalia-8.jpg",
    secondImage: "purse-amalia-8.jpg",
    images: ["purse-amalia-8.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00LIGHTGREY",
    category: "bag",
    color: "grey",
    searchWords: ["poseta"],
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: "casual_elegante",
    firstImage: "P11LIGHTGREY2.jpg",
    secondImage: "P11LIGHTGREY1.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-bag-1",
    category: "backpack",
    color: "black",
    similarColors: ["black", "grey"],
    size: "big",
    material: "-",
    handle: ["strap"],
    style: "casual",
    firstImage: "bag.jpg",
    secondImage: "bag.jpg",
    images: ["bag.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-1",
    category: "wallet",
    color: "blue",
    similarColors: ["blue", "turquoise", "green"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "wallet1.jpg",
    secondImage: "wallet1.jpg",
    images: ["wallet1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-2",
    category: "wallet",
    color: "brown",
    similarColors: ["brown", "orange"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "wallet2.jpg",
    secondImage: "wallet2.jpg",
    images: ["wallet2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-3",
    category: "wallet",
    color: "red",
    similarColors: ["red", "burgundy", "pink"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "wallet3.jpg",
    secondImage: "wallet3.jpg",
    images: ["wallet3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-4",
    category: "wallet",
    color: "green",
    similarColors: ["turquoise", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "wallet4.jpg",
    secondImage: "wallet4.jpg",
    images: ["wallet4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-5",
    category: "wallet",
    color: "red",
    similarColors: ["red", "burgundy", "pink"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: "casual",
    firstImage: "wallet5.jpg",
    secondImage: "wallet5.jpg",
    images: ["wallet5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "B1F00BLACK",
    name: "Bereta modelul 2",
    category: "beret",
    color: "black",
    similarColors: ["black", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "B1BLACK1.jpg",
    secondImage: "B1BLACK2.jpg",
    images: [],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-2",
    category: "beret",
    color: "green",
    similarColors: ["turquoise", "blue", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "beret2.jpg",
    secondImage: "beret2.jpg",
    images: ["beret2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-3",
    category: "beret",
    color: "blue",
    similarColors: ["blue", "turquoise", "green"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "beret3.jpg",
    secondImage: "beret3.jpg",
    images: ["beret3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-4",
    category: "beret",
    color: "grey",
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "beret4.jpg",
    secondImage: "beret4.jpg",
    images: ["beret4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-child-1",
    category: "beret",
    color: "red",
    similarColors: ["red", "burgundy", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual",
    firstImage: "beret5.jpg",
    secondImage: "beret5.jpg",
    images: ["beret5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat1",
    category: "hat",
    color: "violet",
    similarColors: ["violet", "pink", "red"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat1.jpg",
    secondImage: "hat1.jpg",
    images: ["hat1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat2",
    category: "hat",
    color: "cream",
    similarColors: ["cream", "beige", "grey", "white", "yellow"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat2.jpg",
    secondImage: "hat2.jpg",
    images: ["hat2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat3",
    category: "hat",
    color: "brown",
    similarColors: ["brown", "orange"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat3.jpg",
    secondImage: "hat3.jpg",
    images: ["hat3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat4",
    category: "hat",
    color: "beige",
    similarColors: ["beige", "cream", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat4.jpg",
    secondImage: "hat4.jpg",
    images: ["hat4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat5",
    category: "hat",
    color: "grey",
    similarColors: ["grey", "beige", "cream", "white"],
    size: "small",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat5.jpg",
    secondImage: "hat5.jpg",
    images: ["hat5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat6",
    category: "hat",
    color: "cream",
    similarColors: ["cream", "beige", "grey", "white", "yellow"],
    size: "universal",
    material: "-",
    handle: [],
    style: "casual_elegante",
    firstImage: "hat6.jpg",
    secondImage: "hat6.jpg",
    images: ["hat6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
];
