import { productType } from "./types";

export const products: productType[] = [
  {
    key: "P1F00GREEN",
    category: "Geanta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "P1GREEN1.jpg",
    secondImage: "P1GREEN2.jpg",
    images: ["P1GREEN3.jpg", "P1GREEN4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P1F00GREY",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "P1GREY1.jpg",
    secondImage: "P1GREY2.jpg",
    images: [
      "P1GREY3.jpg",
      "P1GREY4.jpg",
      "P1GREY5.jpg",
      "P1GREY6.jpg",
      "P1GREY7.jpg",
      "P1GREY8.jpg",
    ],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P1F00ORANGE",
    category: "Geanta",
    color: "orange",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "big",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "P1ORANGE1.jpg",
    secondImage: "P1ORANGE2.jpg",
    images: ["P1ORANGE3.jpg", "P1ORANGE4.jpg", "P1ORANGE5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P2F00CREM",
    category: "Geanta",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "P2CREM1.jpg",
    secondImage: "P2CREM2.jpg",
    images: ["P2CREM3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P2F00RED",
    category: "Geanta",
    color: "red",
    similarColors: ["red", "visiniu", "pink"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "P2RED1.jpg",
    secondImage: "P2RED1.jpg",
    images: ["P2RED1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P13F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["elegante"],
    firstImage: "purse1.jpg",
    secondImage: "purse1.jpg",
    images: ["purse1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P3F00VISINIU",
    category: "Geanta",
    color: "visiniu",
    similarColors: ["visiniu", "red", "violet"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse-roxen-1.jpg",
    secondImage: "purse-roxen-2.jpg",
    images: ["purse-roxen-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "false",
  },
  {
    key: "P3F00GREEN",
    category: "Geanta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse-roxen-3.jpg",
    secondImage: "purse-roxen-3.jpg",
    images: ["purse-roxen-3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P3F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-roxen-4.jpg",
    secondImage: "purse-roxen-4.jpg",
    images: ["purse-roxen-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P4F00PINK",
    category: "Geanta",
    color: "pink",
    similarColors: ["pink", "visiniu", "violet", "red"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: ["elegante"],
    firstImage: "purse-felicia-1.jpeg",
    secondImage: "purse-felicia-1.jpeg",
    images: ["purse-felicia-1.jpeg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P4F00TURCOAZ",
    category: "Geanta",
    color: "turcoaz",
    similarColors: ["turcoaz", "green", "blue"],
    size: "medium",
    material: "-",
    handle: ["handle"],
    style: ["elegante"],
    firstImage: "purse-felicia-2.jpeg",
    secondImage: "purse-felicia-2.jpeg",
    images: ["purse-felicia-2.jpeg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-sonia",
    category: "Geanta",
    color: "blue",
    similarColors: ["blue", "turcoaz", "green"],
    size: "large",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-sonia-1.png",
    secondImage: "purse-sonia-1.png",
    images: ["purse-sonia-1.png"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P6F00ORANGE",
    category: "Geanta",
    color: "orange",
    similarColors: ["orange", "red", "crem", "brown"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-florina-1.jpg",
    secondImage: "purse-florina-1.jpg",
    images: ["purse-florina-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P5F00RED",
    category: "Geanta",
    color: "red",
    similarColors: ["red", "visiniu", "pink"],
    size: "medium",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-florina-2.jpg",
    secondImage: "purse-florina-3.jpg",
    images: ["purse-florina-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P6F00GREEN",
    category: "Geanta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-florina-4.jpg",
    secondImage: "purse-florina-4.jpg",
    images: ["purse-florina-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P5F00GREEN",
    category: "Geanta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "medium",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse-florina-5.jpg",
    secondImage: "purse-florina-5.jpg",
    images: ["purse-florina-5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00CREM",
    category: "Geanta",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse-andra-1.jpg",
    secondImage: "purse-andra-1.jpg",
    images: ["purse-andra-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00GREEN",
    category: "Geanta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse-andra-2.jpg",
    secondImage: "purse-andra-5.jpg",
    images: ["purse-andra-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P7F00PINK",
    category: "Geanta",
    color: "pink",
    similarColors: ["pink", "visiniu", "violet", "red"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["elegante"],
    firstImage: "purse-andra-6.jpg",
    secondImage: "purse-andra-4.jpg",
    images: ["purse-andra-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00BLUE",
    category: "Geanta",
    color: "turcoaz",
    similarColors: ["turcoaz", "green", "blue"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "purse6.jpg",
    secondImage: "purse6.jpg",
    images: ["purse6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "purse_black_rose.jpg",
    secondImage: "purse_black_rose.jpg",
    images: ["purse_black_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P9F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse_black_rose2.jpg",
    secondImage: "purse_black_rose2.jpg",
    images: ["purse_black_rose2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P8F00GREY",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual"],
    firstImage: "purse_grey_rose.jpg",
    secondImage: "purse_grey_rose.jpg",
    images: ["purse_grey_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P9F00WHITE",
    category: "Geanta",
    color: "white",
    similarColors: ["white", "crem", "bej", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["elegante"],
    firstImage: "purse_white_rose.jpg",
    secondImage: "purse_white_rose.jpg",
    images: ["purse_white_rose.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00GREY",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-1.jpg",
    secondImage: "purse-eliza-1.jpg",
    images: ["purse-eliza-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-2",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-2.jpg",
    secondImage: "purse-eliza-2.jpg",
    images: ["purse-eliza-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-3",
    category: "Geanta",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-3.jpg",
    secondImage: "purse-eliza-3.jpg",
    images: ["purse-eliza-3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-4",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-4.jpg",
    secondImage: "purse-eliza-4.jpg",
    images: ["purse-eliza-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-10.jpg",
    secondImage: "purse-eliza-5.jpg",
    images: ["purse-eliza-8.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00WHITE",
    category: "Geanta",
    color: "white",
    similarColors: ["white", "crem", "bej", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["elegante"],
    firstImage: "purse-eliza-6.jpg",
    secondImage: "purse-eliza-6.jpg",
    images: ["purse-eliza-6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P10F00BEJ",
    category: "Geanta",
    color: "bej",
    similarColors: ["bej", "crem", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-7.jpg",
    secondImage: "purse-eliza-7.jpg",
    images: ["purse-eliza-7.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-purse-eliza-9",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "purse-eliza-9.jpg",
    secondImage: "purse-eliza-9.jpg",
    images: ["purse-eliza-9.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00BEJ",
    category: "Geanta",
    color: "bej",
    similarColors: ["bej", "crem", "grey"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-1.jpg",
    secondImage: "purse-amalia-1.jpg",
    images: ["purse-amalia-1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00PINK",
    category: "Geanta",
    color: "pink",
    similarColors: ["pink", "visiniu", "violet", "red"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-2.jpg",
    secondImage: "purse-amalia-2.jpg",
    images: ["purse-amalia-2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P12F00BLACK",
    category: "Geanta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "small",
    material: "-",
    handle: ["strap"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-3.jpg",
    secondImage: "purse-amalia-10.jpg",
    images: ["purse-amalia-3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00BROWN",
    category: "Geanta",
    color: "brown",
    similarColors: ["brown", "orange"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-4.jpg",
    secondImage: "purse-amalia-4.jpg",
    images: ["purse-amalia-4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00GREY",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-5.jpg",
    secondImage: "purse-amalia-5.jpg",
    images: ["purse-amalia-5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00CREM",
    category: "Geanta",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-6.jpg",
    secondImage: "purse-amalia-6.jpg",
    images: ["purse-amalia-6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00BLUE",
    category: "Geanta",
    color: "blue",
    similarColors: ["blue", "turcoaz", "green"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-7.jpg",
    secondImage: "purse-amalia-7.jpg",
    images: ["purse-amalia-7.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P12F00BLUE",
    category: "Geanta",
    color: "blue",
    similarColors: ["blue", "turcoaz", "green"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-8.jpg",
    secondImage: "purse-amalia-8.jpg",
    images: ["purse-amalia-8.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "P11F00LIGHTGREY",
    category: "Geanta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: ["strap", "handle"],
    style: ["casual", "elegante"],
    firstImage: "purse-amalia-9.jpg",
    secondImage: "purse-amalia-9.jpg",
    images: ["purse-amalia-9.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-bag-1",
    category: "Rucsac",
    color: "black",
    similarColors: ["black", "grey"],
    size: "big",
    material: "-",
    handle: ["strap"],
    style: ["casual"],
    firstImage: "bag.jpg",
    secondImage: "bag.jpg",
    images: ["bag.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-1",
    category: "Portofel",
    color: "blue",
    similarColors: ["blue", "turcoaz", "green"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "wallet1.jpg",
    secondImage: "wallet1.jpg",
    images: ["wallet1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-2",
    category: "Portofel",
    color: "brown",
    similarColors: ["brown", "orange"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "wallet2.jpg",
    secondImage: "wallet2.jpg",
    images: ["wallet2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-3",
    category: "Portofel",
    color: "red",
    similarColors: ["red", "visiniu", "pink"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "wallet3.jpg",
    secondImage: "wallet3.jpg",
    images: ["wallet3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-4",
    category: "Portofel",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "wallet4.jpg",
    secondImage: "wallet4.jpg",
    images: ["wallet4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-wallet-5",
    category: "Portofel",
    color: "red",
    similarColors: ["red", "visiniu", "pink"],
    size: "small",
    material: "-",
    handle: ["handle"],
    style: ["casual"],
    firstImage: "wallet5.jpg",
    secondImage: "wallet5.jpg",
    images: ["wallet5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-1",
    category: "Bereta",
    color: "black",
    similarColors: ["black", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual"],
    firstImage: "beret1.jpg",
    secondImage: "beret1",
    images: ["beret1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-2",
    category: "Bereta",
    color: "green",
    similarColors: ["turcoaz", "blue", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual"],
    firstImage: "beret2.jpg",
    secondImage: "beret2.jpg",
    images: ["beret2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-3",
    category: "Bereta",
    color: "blue",
    similarColors: ["blue", "turcoaz", "green"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual"],
    firstImage: "beret3.jpg",
    secondImage: "beret3.jpg",
    images: ["beret3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-adult-4",
    category: "Bereta",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: [],
    style: ["casual"],
    firstImage: "beret4.jpg",
    secondImage: "beret4.jpg",
    images: ["beret4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-beret-child-1",
    category: "Bereta",
    color: "red",
    similarColors: ["red", "visiniu", "pink"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual"],
    firstImage: "beret5.jpg",
    secondImage: "beret5.jpg",
    images: ["beret5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat1",
    category: "Palarie",
    color: "violet",
    similarColors: ["violet", "pink", "red"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat1.jpg",
    secondImage: "hat1.jpg",
    images: ["hat1.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat2",
    category: "Palarie",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat2.jpg",
    secondImage: "hat2.jpg",
    images: ["hat2.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat3",
    category: "Palarie",
    color: "brown",
    similarColors: ["brown", "orange"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat3.jpg",
    secondImage: "hat3.jpg",
    images: ["hat3.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat4",
    category: "Palarie",
    color: "bej",
    similarColors: ["bej", "crem", "grey"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat4.jpg",
    secondImage: "hat4.jpg",
    images: ["hat4.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat5",
    category: "Palarie",
    color: "grey",
    similarColors: ["grey", "bej", "crem", "white"],
    size: "small",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat5.jpg",
    secondImage: "hat5.jpg",
    images: ["hat5.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
  {
    key: "all-hat6",
    category: "Palarie",
    color: "crem",
    similarColors: ["crem", "bej", "grey", "white", "yellow"],
    size: "universal",
    material: "-",
    handle: [],
    style: ["casual", "elegante"],
    firstImage: "hat6.jpg",
    secondImage: "hat6.jpg",
    images: ["hat6.jpg"],
    description: {
      generalDescription:
        "Geantă de umăr cu finisaj moale și velurat, cu închizătoare de metal în partea de sus. Pliuri cusute și șnur în partea de sus, curea de umăr reglabilă cu cataramă metalică la un capăt. Căptușită.",
      length: 24,
      width: 20,
      height: 20,
      accesorii: "geanta de umar",
    },
    materials: "Este confectionata din",
    stock: "true",
  },
];
